# Generated by Django 3.1.3 on 2021-04-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parts',
            field=models.TextField(default='nothing here', verbose_name='Ингредиенты'),
            preserve_default=False,
        ),
    ]
